// Build script: generates static config.js for production with secure proxy enabled
const fs = require('fs');

const config = {
  SUPABASE_URL: process.env.SUPABASE_URL || 'YOUR_SUPABASE_URL_HERE',
  SUPABASE_ANON_KEY: process.env.SUPABASE_ANON_KEY || 'YOUR_SUPABASE_ANON_KEY_HERE',
  GROQ_API_KEY: 'YOUR_GROQ_API_KEY_HERE', // Intentionally empty: secure proxy is used instead
  USE_SERVER_PROXY: true
};

const output = `/* Auto-generated by build script */\nwindow.CONFIG = ${JSON.stringify(config, null, 2)};\n`;
fs.writeFileSync('config.js', output);
console.log('✓ config.js generated with secure Node.js server proxy enabled');

