// Build script: injects env vars into config.js (only if env vars exist)
const fs = require('fs');

// Only regenerate config.js if GROQ_API_KEY env var is set
// Otherwise, keep the existing committed config.js (has Supabase keys)
if (process.env.GROQ_API_KEY) {
  const config = {
    SUPABASE_URL: process.env.SUPABASE_URL || 'YOUR_SUPABASE_URL_HERE',
    SUPABASE_ANON_KEY: process.env.SUPABASE_ANON_KEY || 'YOUR_SUPABASE_ANON_KEY_HERE',
    GROQ_API_KEY: process.env.GROQ_API_KEY
  };

  const output = `/* Auto-generated by build script */\nconst CONFIG = ${JSON.stringify(config, null, 2)};\n`;
  fs.writeFileSync('config.js', output);
  console.log('✓ config.js generated with GROQ_API_KEY from env');
} else {
  console.log('✓ No GROQ_API_KEY env var found — using existing config.js');
}
